spring:

  datasource:
    password: alura
    username: alura
    url: jdbc:mariadb://localhost:3307/alura1
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  docker:
    compose:
      enabled: true
      file: docker-compose-dev.yaml
      lifecycle-management: start_only




